### ISSUE TITLE
Fbx anf obj files load without material.

### ISSUE THREAD

**Issue by ca-aditi-arora** [chnouman/SceneView#1]
Hi @chnouman , thanks for this Sceneview example. I was looking for this exactly.
However, I'm facing an issue while adding fbx or obj-mtl objects in the assets.
When I add an fbx file and convert it to scenefrom asset and then load it in the scenview there is no material on the object.
But I also saw that you have added a  model.fbx file in the project and I'm guessing the model.sfb file that you are refering in the code is the one that you must have obtained by converting the .fbx into sceneform asset. I can see that your model.sfb files shows material correctly when running the app.
Can you please tell if you did something explicitly to make the material work. Because I've tried many fbx files and I'm not able to load the material in any of them when running the app.
Thanks!

**Comment by chnouman** [comment]
@shiaro007-joker when trying to convert fbx into sfb are you selecting the material as well?

**Comment by chnouman** [comment]
I mean this thing: 

<img width="605" alt="CaptureX" src="https://user-images.githubusercontent.com/15146352/70408534-4da90700-1a6a-11ea-926b-3531e4b57d3e.PNG">

**Comment by ca-aditi-arora** [comment]
@chnouman  Yes I selected the same fbx in the material Path since fbx has the material inbuilt. But it changed to **default** when i clicked Finish. Do I have do put some other path in the material path?

**Comment by chnouman** [comment]
@shiaro007-joker I haven't worked a lot with fbx format but I think there is some way of exporting fbx which makes it compatible with sceneform plugin. I must suggest you should try the GLB format for your models. Glb's are handy in loading from the server as well and had a great textures.
